apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-node-app-deploy
  namespace: type-node-app
  labels:
    app: type-node-app
spec:
  selector:
    matchLabels:
      app: type-node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: type-node-app
    spec:
      containers:
        - name: type-node-app
          image: 445944/type-node-eks
          ports:
             - containerPort: 3000
          env: 
            - name: API_PORT
              value: "3000"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "postgres_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: type-node-service
  namespace: type-node-app
  labels:
    app: type-node-app
spec:
  selector:
    app: type-node-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000



