name: CI/CD for Node.js and PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region us-east-1 --name type-node-app-eks-v4
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/database.yaml
        kubectl apply -f k8s/app.yaml