name: Run Tests and Enforce Merge Rules # Workflow adı

on:
  pull_request: # PR açıldığında veya güncellendiğinde çalıştır
    branches:
      - main  # Hangi branch'e PR açıldığında çalışacağını belirt

jobs:
  run-tests: # testleri çalıştıran job
    runs-on: ubuntu-latest # Hangi işletim sisteminde çalışacağını belirt

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 # Bu kodu main.yml çalıştıracak olan sanal makineye klonlar

    - name: Set up Docker # Docker'ı kurar
      uses: docker/setup-buildx-action@v2
    
    - name: Install docker-compose # Docker-compose'ı kurar
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Node.js # Node.js'i kurar
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Projende kullandığın Node.js sürümü

    - name: Install Dependencies # Projendeki bağımlılıkları yükler
      run: npm install

    - name: Start Docker Services # Docker servislerini başlatır
      run: docker-compose up -d

    - name: Run Tests # Testleri çalıştırır
      run: npm run test-run

    - name: Stop Docker Services # Docker servislerini durdurur
      if: always()
      run: docker-compose down

  enforce-rules: # merge kurallarını uygulayan job
    needs: run-tests # run-tests job'unun tamamlanmasını bekler
    runs-on: ubuntu-latest # Hangi işletim sisteminde çalışacağını belirt
    if: success() 

    steps:
    - name: Merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });

          if (pullRequest.mergeable) {
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'merge', // "merge", "squash" veya "rebase"
            });
          } else {
            throw new Error('Pull request is not mergeable');
          }
        github-token: ${{ secrets.GITHUB_TOKEN }}
